# fly.toml app configuration file generated for duet-morning-meadow-5890 on 2025-12-06T03:29:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'duet-morning-meadow-5890'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 2222
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 2222

  [[services.ports]]
    port = 22

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
